language: python
python:
  - 3.7
  - 3.8
before_install:
  - pip install -U pip
  - pip install -U nose2
  - pip install nose2[coverage_plugin]>=0.6.5
  - pip install codecov
script: nose2 --with-coverage
after_success:
  - codecov
